### ISSUE TITLE
Use relative symbolic links for alternate files?

### ISSUE THREAD

**Issue by jluttine** [TheLocehiliosan/yadm#100]
Why are alternate files using absolute paths for symbolic links? This causes issues when the mount point of the file system changes. For instance, I might mount my disk on a live OS under `/mnt`. I don't see any reason why to use absolute paths, so I thought I'd ask.

**Comment by TheLocehiliosan** [comment]
There _might_ be a reason for this that relates to files located in `~/.ssh`. I simply can't remember though. It is certainly easier in the code to use fully qualified paths, so that may be the reason also.

I can look closer and consider making it relative (or an optionally relative) when other changes are implemented for #90.

**Comment by TheLocehiliosan** [comment]
This is now in the develop branch.
