### ISSUE TITLE
Brace expansion not working in 1.12

### ISSUE THREAD

**Issue by rasa** [TheLocehiliosan/yadm#106]
In TheLocehiliosan's [`.yadm/encrypt`](https://github.com/TheLocehiliosan/example-dotfiles/blob/master/.yadm/encrypt) is
`.ssh/*.{key,pub}`
Unfortunately, brace expansion doesn't work in 1.12. *Neither* the `.key` or `.pub` files get encrypted.

The problem is in line [964](https://github.com/TheLocehiliosan/yadm/blob/4613c1d0c4228b5411ddb854753c2827fc605447/yadm#L964):
```
    for ex_file in ${BASH_REMATCH[1]}; do
```
This doesn't work as the braces are in a variable. The way I found to fix it, is to `eval` it:
```
   eval "parse_encrypt_exclude ${BASH_REMATCH[1]}"
```
A PR is forthcoming.

**Comment by TheLocehiliosan** [comment]
The use of `eval` was removed in b78bb1eef483e5405738567c53e206cf9645e39d. Indeed, in that commit, I've noted that a caveat was that brace and tilde expansion will no longer work in `.yadm/encrypt`. `eval` was removed because of the risk of executing "dirty" data
found in `.yadm/encrypt`. I don't expect to add `eval` again.

I will be diving back into **yadm** development this June, and I'll take a closer look at your PR to see what I can do.

**Comment by rasa** [comment]
Sorry I hadn’t reviewed the history. I will see if there is a way to do this without eval (preferred), or to sanitize the input before calling eval.

**Comment by rasa** [comment]
What if we escaped the special chars via 
```
spec=“$(sed -E 's/([`$&\(|<>;\-])/\\\1/g' <<<“${BASH_REMATCH[1]}”)”
eval "parse_encrypt_exclude $spec”
```
Is that acceptable?

**Comment by TheLocehiliosan** [comment]
@rasa - If this can be implemented in Bash alone, without the `eval` builtin, I think it would be useful. I won't be adding `eval` again, particularly connected to the encrypt feature. I do not want another CVE reported against yadm.

**Comment by TheLocehiliosan** [comment]
Closing this issue for now, as I haven't identified a natural way to support brace expansion without `eval`. If you come up with something, I'd look at a PR.
