### ISSUE TITLE
yadm doesn't respect GNUPGHOME 

### ISSUE THREAD

**Issue by loneprajod** [TheLocehiliosan/yadm#134]
I have `~/.config/gnupg` as my `GNUPGHOME` but yadm keeps creating `~/.gnupg `
I also tried changing `yadm.gpg-program` like this:

```
$ cat ~/.yadm/config
[yadm]
	gpg-program = gpg --homedir ~/.config/gnupg
```

Any idea why it's not working?

**Comment by TheLocehiliosan** [comment]
Yes, I know exactly why this is happening.

First, **yadm** itself is creating a secured .`gnupg` and .`ssh` directory under `$HOME`, to appease concerns of `CVE-2017-11353`. The unfortunate situation is:

1.  **yadm** is unable to inspect the tracked paths prior to cloning
2. When cloning, Git uses the effective umask to establish the permission of directories.
3. There is an tiny window of time between cloning, and **yadm** securing any created directories.

Because of these facts, I have resorted to creating these directories before cloning. This happens regardless of whether or not the repo tracks data in these directories. Even if it was more possible to preview the tracked paths before cloning, it could be argued that there would be a window of time between determining the tracked paths and the clone operation, when the repo could change. Also, because the repo could always begin to track data in these paths, all Git operations assert these directories prior to running. I'm sorry, this only way to shutdown these security complaints completely.

However, you can disable this directory creation using the `yadm.auto-private-dirs` configuration option.

First, add `yadm.auto-private-dirs` to `.yadm/config`, set to false. This will prevent **yadm** from doing this in the future. Second, add `rm -fd ~/.gnupg` to a bootstrap script. This way, when you initially clone your repo, the directory will be created, but when the bootstrap runs, it will be removed (if empty). Further creations of the directory will be prevented by the `yadm.auto-private-dirs` option.

**Comment by loneprajod** [comment]
It worked, thanks.

**Comment by TheLocehiliosan** [comment]
Support for GNUPGHOME var is now in the `develop` branch, and will be part of the next release.
