### ISSUE TITLE
"fatal: this operation must be run in a work tree" after moving home directory

### ISSUE THREAD

**Issue by HarryCutts** [TheLocehiliosan/yadm#144]
I recently renamed my main user on Linux, and moved the home directory to reflect the new username (using the `--move-home` switch to `usermod`). This was after I'd set up my yadm repository, so next time I ran `yadm status` I got some errors:

```
fatal: this operation must be run in a work tree
/usr/bin/yadm: line 903: cd: /home/harryc: No such file or directory
/usr/bin/yadm: line 903: cd: /home/harryc: No such file or directory
/usr/bin/yadm: line 903: cd: /home/harryc: No such file or directory
```
(`harryc` being the old user name.)

Fixing this is relatively simple; you just update the `worktree =` line in `.yadm/repo.git/config` to reflect the new home directory. Is there some way that yadm can fix this automatically, or avoid having the absolute path?

**Comment by TheLocehiliosan** [comment]
When **yadm** does a `clone` or `init`, it sets the work tree to the value specified by `-w` (or more likely to `$HOME` if unspecified). At that moment, the value because a configuration local to the yadm repository. The programatic way to change the value is:

```
yadm gitconfig core.worktree <NEW PATH>
```

I believe you _can_ use a relative path if you really want to, but it must be relative to the repo directory.

It might be possible to change yadm to use a relative path when doing a clone or init. It would need some portable code written to work out the relative paths between the repo dir and home dir. But I think if users specified a work-tree with `-w` that should always be an absolute path. I'll have to think about this some more.
