### ISSUE TITLE
"error setting certificate verify locations"

### ISSUE THREAD

**Issue by OmriSama** [TheLocehiliosan/yadm#152]
### This question is about

* [ ] Installation
* [x] Initializing / Cloning
* [ ] Alternate files
* [ ] Jinja templates
* [ ] Encryption
* [ ] Bootstrap
* [ ] Hooks
* [ ] Other

### Describe your question
I seem to be having an issue using Yadm on non-Ubuntu or Debian based environments.

I installed Yadm earlier on my Mac via Brew, and on Cygwin via git-cloning the repository.
I was able to clone [my dotfiles repo](https://github.com/OmriSama/dotfiles), but afterwards, I tried to execute `yadm pull --rebase`, only to be greeted with the following error:

```shell
$ yadm pull --rebase
fatal: unable to access 'https://github.com/OmriSama/dotfiles.git/': error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
$ 
```
Interestingly enough, this was the same error on both macOS and Cygwin.

Any help would be appreciated!

**Comment by TheLocehiliosan** [comment]
At first it looked like there was something wrong with the CA certificates on your system(s). However, looking at the contents of your dotfiles, I see this in your `.gitconfig`:

```
sslCAinfo = /etc/ssl/certs/ca-certificates.crt
```

I haven't looked closely, but I suspect this is not the standard path for MacOS or Cygwin. I suggest removing this. The system's root certificates should be used by default if the systems are configured properly (including Ubuntu/Debian).

I think Git's `http.sslCAinfo` config is usually only used when you are communicating with a repo that uses a certificate that is self-signed or otherwise not verifiable via the standard CA certs.

If you truly need to set that for some of your systems, I suggest using the "Alternate Files" feature of **yadm** to define the `http` section of .gitconfig, and then include that alternate file in the main `.gitconfig`.

**Comment by OmriSama** [comment]
> 
> 
> At first it looked like there was something wrong with the CA certificates on your system(s). However, looking at the contents of your dotfiles, I see this in your `.gitconfig`:
> 
> ```
> sslCAinfo = /etc/ssl/certs/ca-certificates.crt
> ```
> 
> I haven't looked closely, but I suspect this is not the standard path for MacOS or Cygwin. I suggest removing this. The system's root certificates should be used by default if the systems are configured properly (including Ubuntu/Debian).
> 
> I think Git's `http.sslCAinfo` config is usually only used when you are communicating with a repo that uses a certificate that is self-signed or otherwise not verifiable via the standard CA certs.
> 
> If you truly need to set that for some of your systems, I suggest using the "Alternate Files" feature of **yadm** to define the `http` section of .gitconfig, and then include that alternate file in the main `.gitconfig`.

Wow. 
You're much more observant than me. *facepalm*

thank you so much lol
