### ISSUE TITLE
Can yadm implement an include mechanism for config files?

### ISSUE THREAD

**Issue by infokiller** [TheLocehiliosan/yadm#16]
Sorry if was already covered in the docs - I went over the README and didn't understand this.

## Background

There are programs like `i3` that neither have an include mechanism, nor allow you to do the configuration based on the host/os (there's no if/else logic). In addition, it's sometimes undesirable to put all the config in the same file. For example, I can't put work related configuration in the same files because it might be confidential, but I want to share my dotfiles on github. This means that files must be split to multiple repos.
Does yadm support this use case? let's use i3 configuration as an example. Ideally, I'd be able to work with the following files:

*  `.i3config` - my regular i3 config with common stuff, stored in one repo/branch.
* `.i3config_work` - an i3 config file specific to my work, stored in another repo/branch.

Is it possible to have yadm concatenate these files for me automatically, based, for example, on the hostname?

Thanks!

**Comment by TheLocehiliosan** [comment]
**yadm** only operates on files that either exist in its repository, or are in the encrypted archive it uses (the encrypted can also be part of the repository).

**yadm** does not support mixing data from multiple repos.

Initially I thought that you could use **yadm**'s alternate file symlinks, and put the confidential version in the encrypted file archive. However, I just looked at it a bit closer, and alternates are only processed for files which exist in the repository. I think it would be relatively easy to update the alternates processing to also include encrypted files. If I made that change, you could probably do the following:

`.yadm/encrypt` contains:
```
path/i3config##Linux.workhost
```

Add your normal i3config with the name `path/i3config##` (this is added to the **yadm** repo)

Add your work i3config with the name `path/i3config##Linux.workhost` (this gets encrypted using `yadm encrypt`)

In this way, `yadm decrypt` would extract your "work version" from the encrypted archive. **yadm** would also have your default version from what is maintained in the repository. And **yadm**'s alternates system would symlink `path/i3config` to the appropriate and available version.

Again, this strategy will not work with **yadm** as it is today because the `Linux.workhost` version would not be considered by the alternates system.

I'm sorry if this answer is very confusing. I'm trying hard to be clear. Would this type of change be useful for your use case?

If you truly want to maintain these files in multiple repos, perhaps a tool like [vcsh](https://github.com/RichiH/vcsh) could fit your needs?

**Comment by infokiller** [comment]
Thanks for your thorough response!

Here's my understanding, please correct me if I'm wrong:

There are two separate issues here:
* Using the encrypted file archive for host specific configuration
* Supporting an include mechanism for config files

The type of change you propose will fix the first issue, but the second issue will remain, right?

I'll take a harder look at `vcsh` and let you know.

**Comment by TheLocehiliosan** [comment]
I'm not suggesting adding any type of "include" or "template" processing within **yadm**. I'm suggesting maintaining separate versions of the file. In addition, with a small change, certain versions of the files could be maintained the the encrypted archive (which could be part of the repo, or maintained outside of the repo as some do).

vcsh supports maintaining separate versions of a file, maintained in separate repos. Then choosing which repos you'll include.

**Comment by TheLocehiliosan** [comment]
It just dawned on me, that it may be possible to use git submodules to handle some of this. This may sound a bit complicated, but the general scheme would be:

Use git submodules with **yadm** to manage the files you want excluded from the repo in a separate repository (this repo could be a private repo). Then, if you want **yadm** to choose which directory to use, you could create symbolic links named with the `##Linux.hostname` convention, and the appropriate link would be used. The result would be a symlink that points to a symlink that points to your directory. Anyhow, if it sounds like something worth exploring, I could probably create an example to look at.

**Comment by infokiller** [comment]
Sounds worth exploring, but I want to make sure I understand- let's say I want to customize my `.bashrc` file this way for two Linux machines: `public_machine` and `private_machine`. Then, I will need to include the following in my **yadm** repo:
* A git submodule `my_private_repo` that contains the files for the private repo.
* `.bashrc##Linux.public_machine` - regular bashrc file specific to `public_machine`.
* `.bashrc##Linux.private_machine` - symlink to `my_private_repo/.bashrc`.

Is that correct?

Thanks!

**Comment by TheLocehiliosan** [comment]
Yes, I think you understood correctly. And in case this wasn't clear, the submodule should be supported already by **yadm**. I think the process would be to run:

    yadm submodule add <repo URL> ~/my_private_repo

Then `yadm commit` to commit the submodule configuration to the **yadm** repo. Also when cloning, it will be necessary to do a `yadm submodule init` and `yadm submodule update`. Of course this is all built into Git. I just wanted to point out that the **yadm** repo itself can track the other repository.

This whole strategy isn't really the intended scenario for **yadm**, but I believe using submodules would work.

**Comment by TheLocehiliosan** [comment]
@infokiller Hi, I'm not sure if you're still interested in this problem, but a new feature released today _may_ be another way to address this. Specifically I'm referring to

> There are programs like i3 that neither have an include mechanism, nor allow you to do the configuration based on the host/os (there's no if/else logic).

**yadm** can now process Jinja2 templates if you have `envtpl` installed. This means you could have if/else blocks inside configuration files which don't support them natively.

Cheers

**Comment by infokiller** [comment]
Thanks a lot @TheLocehiliosan !
That sounds like a great feature, I'll definitely take a look when I get a chance.
