### ISSUE TITLE
GIT_WORK_TREE not set by `yadm enter`

### ISSUE THREAD

**Issue by hholst80** [TheLocehiliosan/yadm#160]
### Describe the bug

`yadm enter` does not set the `GIT_WORK_TREE` environment variable.

### To reproduce

setup yadm as usual and run `yadm enter`. inspect variables with `env|grep GIT` and see that `GIT_WORK_TREE` is not defined as expected. This makes some tooling integrated with `git` not work such as https://git-cola.github.io/

This variable should probably be set also for running "external" commands if `yadm cola` is executed directly.

**Comment by davvid** [comment]
I agree it would be good to fix this.  It seems like yadm always chdirs to the `$YADM_WORK` (aka `$HOME`) directory internally, so exporting `GIT_WORK_TREE` to that same value seems like a good idea in general.

That said, I just tweaked cola so that it uses the current directory as the worktree when only `GIT_DIR` has been exported in the environment.  https://github.com/git-cola/git-cola/commit/499d914a9836951f270afe6504b2c5cf071daa4e

Please test that out (without any wrapper script that might be setting `GIT_WORK_TREE`) and it should work correctly now under `yadm cola`.

The easiest way to test is to clone the repo and add its `bin` directory to your `$PATH`, or add a symlink to `.../bin/git-cola` in your `$PATH` ahead of any system version you might have installed in `/usr/bin`.  @hholst80  let me know if that gets cola working for you without any extra setup.

**Comment by TheLocehiliosan** [comment]
I don't see any trouble with populating `$GIT_WORK_TREE`. I think most tools do not need this because they also respect the `core.worktree` repo configuration. I believe `$GIT_WORK_TREE` is technically a method to override the `core.worktree` config.

I can make a change to have `yadm enter` inspect the `core.worktree` config, and add it to the environment.

**Comment by TheLocehiliosan** [comment]
This has been added to the `develop` branch, and will be in the next release.
