### ISSUE TITLE
Website Getting Started page could be clearer, and actually doesn't work

### ISSUE THREAD

**Issue by jwatt** [TheLocehiliosan/yadm#169]
The [Getting Started](https://yadm.io/docs/getting_started) page says:

```
Eventually you will want to push the local repo to a remote.

yadm remote add origin <url>
yadm push -u origin master
```

It wasn't clear to me whether to expect the `yadm` wrapper to be smart enough to exclude the internal repo path from `<url>` or not. It turns out it is not. Perhaps it would be clearer to use `<user@host:.yadm/repo.git>` rather than the ambiguous `<url>`.

Even after doing that, it turned out that the `yadm push` command fails since it is rejected.

I should say first that since the text under discussion belongs to the "If you don’t currently have a repository" section, I assumed it to be reasonable to simply initialize the machine I was pushing to with `yadm init` (although the docs don't specify to do this, in seems necessary since yadm appears to set permissions etc. and so a clone from the local machine to the remote without an init on the remote first wouldn't do the right thing).

With that done, the push was rejected. I though maybe running `yadm config receive.denyCurrentBranch warn` on the remote machine would work to fix it, but that appears to be silently dropped. Instead I had to run git directly via `(cd .yadm/repo.git && git config receive.denyCurrentBranch warn)`. That done, pushing from the local machine then worked.

**Comment by TheLocehiliosan** [comment]
This is the first I’ve had this reported as confusing. And I will look to see if it can be clarified. However, URL should be the value of a git remote. For example, a Github, Bitbucket, or Gitlab URL. Or users that want to host their own repo would have another git:// or file:// url of a bare repo they have created. 

yadm is a client for interacting with a remote repo, but if you want to generate a remote repo, you need to use git or one of the many git repo hosting sites on the internet. 

The local repo used by yadm isn’t suitable to receive updates because it has a work-tree defined (similar to most git repos anyone clones). If you want a repo to push to locally it will need to be created with `git init --bare`.

Does this information help clear up some confusion?

**Comment by TheLocehiliosan** [comment]
Also, `yadm config` is for setting yadm configurations. If you want to change a config for the local repo you can run `yadm gitconfig` instead.

**Comment by jwatt** [comment]
Hi Tim. Thanks for the helpful reply and sorry I didn't reply at the time.

I think my confusion stemmed from trying to get yadm to push from my original workstation directly to a new workstation that I was setting up without creating and going through a third, bare, intermediary repository (as the docs basically assume). The intention was to push/pull directly between these workstations/yadm repos.

This is what worked for me:

```
# on new machine:
yadm init
yadm gitconfig receive.denyCurrentBranch warn  # temporary, to allow push to be recieved

# on original machine
yadm remote add newmachine <url>
yadm push -u newmachine master

# on new machine:
yadm gitconfig --unset receive.denyCurrentBranch
yadm reset --mixed  # so that `yadm status` can be used to check for conflicts
yadm status  # check for conflicts (files marked "modified")
yadm diff -R <modified-file>  # use to note/save changes you'd like to keep
yadm reset --hard  # force dotfiles to state from original machine
# now manually apply any changes you saved
```

Would it be worth adding a section to the docs on this "direct" push usecase?
