### ISSUE TITLE
Unnecessary creation of `$HOME/.gnupg`

### ISSUE THREAD

**Issue by marcfrederick** [TheLocehiliosan/yadm#171]
### Describe the bug

yadm creates the `$HOME/.gnupg` directory on every push/pull.

### To reproduce

1. Make sure you don't have a `$HOME/.gnupg` directory.
2. Run command 'yadm pull'
3. An empty directory has been created.

### Expected behavior

Don't create this directory unless necessary

### Environment

 - Operating system: macOS 10.15.1
 - Version yadm: 1.12.0
 - Version Git: 2.21.0 (Apple Git-122)

**Comment by TheLocehiliosan** [comment]
This is (presently) intentional. It can be disabled using the `yadm.auto-private-dirs` configuration option. This was added to deal with a CVE raised. I will leave this issue open, and attempt to deal with the concerns of the CVE in a less obtrusive way.

For now run `yadm option yadm.auto-private-dirs false`, and be sure to track the `.yadm/config` file.

**Comment by marcfrederick** [comment]
> For now run `yadm option yadm.auto-private-dirs false`, and be sure to track the `.yadm/config` file.

@TheLocehiliosan I'm getting an error on that one: `git: 'option' is not a git command. See 'git --help'.`

**Comment by TheLocehiliosan** [comment]
@marcfrederick Sorry, I should have written:

`yadm config yadm.auto-private-dirs false`

"option" is wrong...

**Comment by TheLocehiliosan** [comment]
I've updated the code for the next release to reduce this type of directory creation to a minimum. I will also improve the documentation about what directories are created, and why.

**Comment by TheLocehiliosan** [comment]
Now, web documentation has been updated for the next release.
