### ISSUE TITLE
Update to yadm 2.x breaks links

### ISSUE THREAD

**Issue by fho** [TheLocehiliosan/yadm#183]
### Describe the bug

I updated from yadm 1x to yadm 2.0.1.
After the update, all configuration files that used links were broken.

So far I was using the alternative filename format:
`<filename>##<OS>.<HOSTNAME>`. This worked fine.

In yadm 2.0.1 the syntax seem to have changed and the syntax is not supported anymore.
I have to rename the files to `<filename>##os.<OS>,hostname.<HOSTNAME>`

This took some time to figure it out.

### Expected behavior

It would be great if either:
- the same alternative filename format is supported then in version 1 or
- that the `yadm upgrade` command renames my existing files or
- that `yadm upgrade` informs me that I have to rename the files

**Comment by TheLocehiliosan** [comment]
I'm sorry this has caused you trouble. I want to improve this.

yadm uses [semantic versioning](https://semver.org), which updates the MAJOR version when API breaking changes are made to the software. I included all of those types of changes in the 2.0.0 release. The changes have been documented. When first running 2.x.x, a user should be presented with information that includes the URL: https://yadm.io/docs/upgrade_from_1 (which documents the API breaking changes). I *do* think this can be improved.

You've listed three possibilities above: 1. support old names 2. upgrade renames alternates. 3. upgrade warns about alternates.

I'm going to discount the first option. The old names are just too incompatible with the scoring method used by the new system. I considered this option a lot during the development.

The second option is challenging. `upgrade` doesn't touch potential alternate files because in many cases it is unclear about what the alternate file represents. For example `file##x` could mean an OS or CLASS that is "x". Maybe it's possible to rename the ones that start with the wildcard `##%.`, but then it only handles the problems for some (and the least frequent cases).

The third option seems best. I think it makes sense to warn users (while upgrading or otherwise) when alternatives exist that are invalid. That is, if a file is tracked which contains `##`, but does not use a known "label", then a warning message is displayed for the user, with a link to documentation about the correct naming convention.

**Comment by fho** [comment]
@TheLocehiliosan I somehow totally missed the upgrade guide.
Showing a warning when a link has an invalid name would be a great solution.

Thanks for the help and the great yadm tool in general! :-)

**Comment by TheLocehiliosan** [comment]
These warnings have been added to the `develop` branch, and will be part of the next release.
