### ISSUE TITLE
Alternate files and templates processing not working on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by kyeongsoo** [TheLocehiliosan/yadm#191]
The title says it all.
Now I am migrating my dotfiles from my own git repository with custom shell scripts to yadm. It works greatly on Arch Linux (LSB ver. 1.4), but after cloning it on Ubuntu 18.04 LTS, I found that the alternate files and templates not work at all, even with "yadm alt".

I have the following files under yadm on Arch:
.bash_aliases
.bash_aliases##template
.gitconfig -> .gitconfig##os.Linux
.gitconfig##os.Linux

As you can see, yadm correctly process alternate files and templates, but on Ubuntu, none work at all; 'yadm alt' does not show any message either.

Note that yadm versions on Arch and Ubuntu are 2.3.0-1 and 1.12.0-1, respectively.

**Comment by TheLocehiliosan** [comment]
The 1.x.x and 2.x.x versions of yadm do no use the same alternate naming convention. You can compare the documentation between [1.12.0](https://github.com/TheLocehiliosan/yadm/blob/1.12.0/yadm.md#ALTERNATES) and [2.3.0](https://github.com/TheLocehiliosan/yadm/blob/2.3.0/yadm.md#ALTERNATES). These are not compatible (which is why the major version number changed from 1 to 2). Arch seems to adopt new versions quicker than Ubuntu. I can offer the following suggestions:

1. Use a newer version of yadm on Ubuntu, instead of the older packaged version. yadm is merely a single file Bash script which you can download directly. You could even include a version of yadm in your dotfiles repo.
2. Take it one step further, and include the [TheLocehiliosan/yadm](https://github.com/TheLocehiliosan/yadm) repo as a submodule within your dotfiles.
3. Change your alternate files to use the old 1.x.x naming convention, and export a variable `YADM_COMPATIBILITY=1`. This will cause the 2.x.x to use the old naming convention. This will stop being supported in some future release, but for now a version 1 compatibility mode is part of yadm 2.x.x.

If interested in a way of cloning a dotfiles repo without yadm installed yet (for example, it being "part" of your dotfiles), you can checkout [bootstrap.yadm.io](https://bootstrap.yadm.io).
