### ISSUE TITLE
add support for machine type for alternates

### ISSUE THREAD

**Issue by danieldc** [TheLocehiliosan/yadm#21]
The current version of alternates support variations based on OS (Darwin, Linux, etc), host name and user. This helps use cases which are specific to a given OS, machine name, or a user.

Will it be possible to add another variation that is based on a "machine type" concept? This way a file name can be specialized not only based on OS/machine/user, but also on "machine type".

Here is a made up example to illustrate what I mean:

``` shell
$ cat ~/yadm_type
work
$ ls -l foo*
... foo -> foo##work#Darwin.host1.user_name
... foo##work#Darwin.host1.user_name
... foo##home#Linux.host1.user_name
$ echo -n home > ~/yadm_type
$ cat ~/yadm_type
home
$ ls -l foo*
... foo -> foo##home#Darwin.host1.user_name
... foo##work#Darwin.host1.user_name
... foo##home#Linux.host1.user_name
```

**Comment by TheLocehiliosan** [comment]
It is certainly possible to add this type of feature.

I don't think I fully understand your use case though. Perhaps you could explain it more. Your example uses a manually maintained file to provide a "classification" to be used for alternates. Is this something that you plan on changing from time to time; to "change" the classification based on your activity? Or is this something that would be more permanent? It's rather unusual that OS/hostname/user would be duplicated across distinct systems, is that your situation? Or is it more a case of wanting a set of machines to share a single classification, but they don't line up across OS?

In the past I've considered adding a feature that allowed the manual "override" of "OS" or "Hostname" or "User" for the alternates system. My idea was to have the overrides be set using a **yadm** command. If set, the alternates system would use that value instead of the normal one. With such a feature you could do something similar to this:

    $ yadm override os work
    $ ls -l foo*
    ... foo -> foo##work
    ... foo##work
    ... foo##home
    ... foo##Darwin
    $ yadm override os home
    $ ls -l foo*
    ... foo -> foo##home
    ... foo##work
    ... foo##home
    ... foo##Darwin
    $ yadm override --unset os
    $ ls -l foo*
    ... foo -> foo##Darwin
    ... foo##work
    ... foo##home
    ... foo##Darwin

The actual implementation would be to store these values inside the **yadm** repo configuration—which is distinct on each system, but not separate from the **yadm** data (`~/.yadm/repo.git/config`).

**Comment by danieldc** [comment]
Thank you for the quick reply.

>> Or is it more a case of wanting a set of machines to share a single classification, but they don't line up across OS?

Yes, this is the use case I am talking about. The intent for ~/yadm_type file was about illustrating the use case, rather than specifying an implementation, even though I do believe is good to have it that way because is generic (side note: the file would be better named ~/machine_type), can can be used in different contexts.

It's common for me (and presumably other people) to work with different machines (phy, virtual, containers, etc) running different OSes, but sharing some categorization other than OS, hostname, or user.

Ex: at work, I'm using linux, mac/bsd, and cygwin, some for doing dev work, some for testing. At home, similar mix of OSes, and some different usage as well (dev work, infra, plain).
I would like to split the machines to: work_dev, work_test, home_dev, home_infra, and home_plain. This way, a mac machine at home for dev work will get the xxx##home_dev#Darwin file variation. The 3 test machines at work will get the xxx##work_test#{os}.{hostname} file variation (for testing some distributed service who needs an individualized config file).

**Comment by TheLocehiliosan** [comment]
Thanks for the additional information. I do think that simply overriding the existing classifications would probably work what you want to achieve. However, I can conceive of situations where you would want some files to work with a general classification, and other files to will work based on the actual `OS`, and mixing the two wouldn't' be possible.

So I think I will plan to implement an additional level of classification called `Class`. `Class` is manually set via a **yadm** command. `OS`, `Hostname`, `User` are dynamically determined, but can also be manually overridden via a **yadm** command. The order of precedence would be `Class`, `OS`, `Hostname`, and finally `User`.

`Class` will be an optional member of the hierarchy. This way users are not forced to use `Class` and current implementations will work without changes.

The new list of supported file suffixes would be:

    ##
    ##Class
    ##Class.OS
    ##Class.OS.Hostname
    ##Class.OS.Hostname.User
    ##OS
    ##OS.Hostname
    ##OS.Hostname.User

Additionally, **yadm** will recognize a wild card for any of these classifications. This would make it possible to do things like have a file match when a specific `User` is detected regardless of the other classifications.

I'm not sure how quickly I will be able to implement the changes, but they will
likely go into version `1.06`.

**Comment by TheLocehiliosan** [comment]
I'm going to publish `1.06` before this feature is ready. These features will become part of `1.07`. Sorry for the delay.

**Comment by danieldc** [comment]
Not a problem, and thank you for keep looking into this!
