### ISSUE TITLE
All yadm git commands seem to have a delay after executing 

### ISSUE THREAD

**Issue by jlehrer1** [TheLocehiliosan/yadm#235]
### Describe the bug
Running any yadm git command, i.e. `yadm status`, outputs correctly immediately, but then delays for a second before completing the command. This makes each command take about `1.5s-2s` to run completely, which feels very slow when trying to do any typical git workflow. Additionally, git commands in regular repositories execute in `~.02s`, which is an especially stark contrast. 

### To reproduce. 
Run yadm git commands and time them.   

### Expected behavior
Yadm git commands output correctly and then finish.
 
### Environment

 - Operating system: [Ubuntu 18.04, yadm/testbed, etc.] macOS 10.15.5
 - Version yadm: [found via `yadm version`] 2.4.0
 - Version Git: [found via `git --version`] git version 2.24.3 (Apple Git-128)

### Additional context
If this is expected behavior, that's no problem, I'm just curious as to why this is.

**Comment by TheLocehiliosan** [comment]
Hi, I believe this time is proportional to the size of your repo. I took a quick look at your dotfiles repo, and you're tracking 9248 files (which is unusually high for dotfiles). The extra time is likely due to evaluating every one of those files to see if it should be processed for "alternates" or "templates". You can disable this automatic processing like so:

`yadm config yadm.auto-alt false`

Can you try that and see if it fixes the delay you are experiencing?

If it does, you can commit that `.config/yadm/config` to your repo and it will automatically be configured everywhere. It doesn't look like you are using alternate processing, but even if you disable auto-alt, you can still manually run the alternate processing with the `yadm alt` command.

**Comment by jlehrer1** [comment]
Yeah, that does fix the delay. Thank you very much!

**Comment by TheLocehiliosan** [comment]
@jlehrer1 I'm glad that helped. Thanks for bringing this up. I'll likely add something to the FAQ in case others encounter the same issue. 

Cheers.
