### ISSUE TITLE
Finding correct .yadm directory automatically?

### ISSUE THREAD

**Issue by jluttine** [TheLocehiliosan/yadm#27]
Hi, I just found yadm and it seems just perfect. Works nicely with dotfiles in home directory. However, I would like to use yadm for another directory (namely /etc/nixos). I was wondering if there is some easy supported way of doing this?

I ran `yadm init` as root in `/etc/nixos` and it initialized `/root/.yadm`. In file `/root/.yadm/repo.git/config`, I changed `worktree` to point to `/etc/nixos` instead of `/root`. Now, yadm manages files in `/etc/nixos`. If I also wanted to have `.yadm` directory under `/etc/nixos`, I need to use `-Y /etc/nixos` for all yadm commands, I suppose. Or is it possible to make `yadm` detect if there's `.yadm` directory under the current working directory or its parent directories and then use that automatically? Or do you have any suggestions on how to handle this setup?

I'm quite happy with the current setup where I manually modified `/root/.yadm/repo.git/config` and let `.yadm` be under `/root` but I'm just wondering if I could improve on this in case yadm has some built-in support.

Thanks a lot for yadm in any case! :+1:

**Comment by jluttine** [comment]
Oh, just found this file: https://github.com/TheLocehiliosan/yadm/blob/master/yadm.md. So `-w` switch for `init` at least sets the working directory, nice!

**Comment by jluttine** [comment]
So just to clarify my remaining question: is it possible to make yadm automatically detect which yadm to use if it's not `$HOME/.yadm` but other `.yadm` directory inside the current working directory or its parent directory? Plain git handles this by finding the appropriate `.git` directory so I was wondering if yadm supports it too.

**Comment by TheLocehiliosan** [comment]
I don't think **yadm** should do this type of directory searching. It's true that **yadm** works different from Git in this way, but it's very deliberate. I want **yadm** to be a command which can run from any directory, but still work the same. Often when dotfiles are changed, it is due to a new situation which is being handled in the moment. Running **yadm** from your current directory allows you to stay focused on the task you're in the middle of, and doesn't require a context shift.

What do you think about creating aliases for **yadm** which equate to `yadm -Y DIR` ?

        alias yadm="yadm -Y DIR"

**Comment by jluttine** [comment]
Ok, good to know it's deliberately not supported. I'll consider creating aliases, perhaps something simple like:
```alias yadm="yadm -Y `pwd`/.yadm"```
Thanks!
