### ISSUE TITLE
`yadm config` doesn't appear to work

### ISSUE THREAD

**Issue by karma0** [TheLocehiliosan/yadm#31]
This is what I'm seeing:

```bash
[karma0:~] % yadm config user.name Bobby   
[karma0:~] % yadm config user.email karma0@gmail.com
[karma0:~] % yadm commit -am "Initializing"         

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <(null)>) not allowed
```

**Comment by karma0** [comment]
For others: I was able to circumvent the issue by doing the following:

```bash
cd ~/.yadm/repo.git
git config --local user.email karma0@gmail.com
git config --local user.name Bobby
cd -
yadm commit -am "Initializing"
```

**Comment by TheLocehiliosan** [comment]
This behavior is intended.

Most **yadm** users already have these options in a "global" Git configuration. Indeed, running the Git commands suggested by the "Tell me who you are" message would solve this problem by creating a "global" configuration.

The suggestion you made above creates these configurations local to the **yadm** repository. That can be done more simply using a `yadm gitconfig` command. However, a "global" config option is a better choice (particularly if the `.gitconfig` is managed by **yadm** because it will not have to be configured every time the repo is cloned.

The preferred solutions to your problem would be one of these:

1. Set "global" configuration options in `~/.gitconfig`

        git config --global "user.email" "your-email@domain"
        git config --global "user.name"  "Your Name"

    or

        yadm gitconfig --global "user.email" "your-email@domain"
        yadm gitconfig --global "user.name"  "Your Name"


2. Set "repo-only" configuration options in the **yadm** repo

        yadm gitconfig "user.email" "your-email@domain"
        yadm gitconfig "user.name"  "Your Name"

The second option accomplishes the same result as your initial suggestion, although it is done using `yadm gitconfig` commands. Again, this second solution would need to be done each time you clone the repository.

**Comment by TheLocehiliosan** [comment]
Thanks for bringing up a possibly confusing point for users. I will add some of this information to the online documentation.
