### ISSUE TITLE
Include git version in yadm --version

### ISSUE THREAD

**Issue by xeruf** [TheLocehiliosan/yadm#377]
### Is your feature request related to a problem? Please describe.

For bug reports and stuff, you gotta list both versions, so why not make it more convenient.

### Describe the solution you'd like

```sh
❯ yadm --version
yadm 3.1.1 using git 2.33.0
```

**Comment by lucacavallaro** [comment]
It is trivial to implement this by enhancing the `yadm version` command, but this type of feature can easily be implemented as a [hook](https://yadm.io/docs/hooks) as well.

In this specific case you can add a file called `post_version` in the `.config/yadm/hooks` folder containing a simple script like:

```sh
#!/bin/sh
git --version
```
So that, once the script has been made executable (`chmod +x post_version`), the `yadm version` command returns

```sh
➜  ~ yadm version
yadm 3.1.1
git version 2.30.1 (Apple Git-130)
```

**Comment by TheLocehiliosan** [comment]
This has been updated in the `develop` branch, and will be included in the next release.
