### ISSUE TITLE
Add support for jinja2-cli for Jinja Templating

### ISSUE THREAD

**Issue by KyleKing** [TheLocehiliosan/yadm#428]
### This issue is about

* [x] Man pages or command-line usage
* [x] Website documentation
* [ ] Packaging
* [ ] Other

### Describe the issue

- Per #159, `envtpl` is no longer recommended
- However, [`j2cli`](https://github.com/kolypto/j2cli) hasn't received any new releases since Jul2019 (and doesn't work for me when I just tried it)
- But development has continued on the project that initially inspired `j2cli`, [`jinja2-cli`](https://github.com/mattrobenolt/jinja2-cli), which would be a drop-in replacement, if supported by yadm

**Comment by rasa** [comment]
Re envtpl, https://github.com/envtpl/envtpl/commits/master shows a lot of recent activity, with [four](https://github.com/envtpl/envtpl/releases) releases in the last few months. 

Also, https://github.com/metwork-framework/envtpl says it's a "maintained fork" and has [78 commits](https://github.com/envtpl/envtpl/compare/master...metwork-framework:envtpl:master) since being forked.

**Comment by KyleKing** [comment]
Oh! I didn't even check. Let me try that out. Would be awesome if envtpl does work

**Comment by KyleKing** [comment]
Yeah, `envtpl` works! I thought I had seen the documentation say that `envtpl` was no longer maintained, but it is correct on the site, so glad to be wrong

Anyway, closing because `envtpl` works, so supporting `jinja2-cli` isn't necessary
