### ISSUE TITLE
Offer bootstrap after clone

### ISSUE THREAD

**Issue by TheLocehiliosan** [TheLocehiliosan/yadm#45]
After a successful clone, offer to run the `bootstrap` command (if it exists post-clone). Also add options to the `clone` command to force `bootstrap` to run or prevent `bootstrap` from running without any prompting.

**Comment by mipimipi** [comment]
Hi,
just a question about this feature: As far as I understand it from the posts above, the feature would allow to execute some logic after cloning. Could this be used to handle the config directories of Firefox and Thunderbird properly? Both programs store their config in a directory named `<some-generated-8-letter-ID>.default`. The generated ID is unique for each installation. So, in order to use a config directory from a yadm repo for a newly installed FF or TB, some logic is needed to rename the config folder.
Thanks, mipi

**Comment by mipimipi** [comment]
Sorry, just saw, that the feature is already implemented. It would be nice if my question could still be answered. Thanks!

**Comment by TheLocehiliosan** [comment]
@mipimipi If you can program it (or script it) it can be done. If a bootstrap exists, it will be executed after a successful clone.

Perhaps symlinking your directory to the machine specific name would be a good solution.
