### ISSUE TITLE
overwrite YADM_REPO

### ISSUE THREAD

**Issue by fdietze** [TheLocehiliosan/yadm#5]
Hi, I'd like to store my repo in a custom path. Overwriting YADM_REPO seems straight-forward. Does that cause any problems? If not, I'd prepare a PR.

**Comment by TheLocehiliosan** [comment]
Very soon I am publishing a version of *yadm* which understands a `-Y <dir>` parameter, which allows you to specify a custom `YADM_DIR`. The repository is still held in `YADM_DIR/repo.git`.

For example, doing this:

    yadm -Y /mypath init

would use the following paths:

Repo: `/mypath/repo.git`
Config: `/mypath/config`
Encrypt Config: `/mypath/encrypt`
Encrypted Data: `/mypath/files.gpg`

Will this help you out?

If not, can you explain your use-case in a bit more detail?

**Comment by fdietze** [comment]
I have a private and a public dotfiles repo, which I both check out in my home folder. The repos themselves are located in my project folder. Git alone can do this already, so I'm using yadm only for creating the host-agnostic symlinks.

Right now I replaced the variable assignments at the top of yadm with:
```bash
if [ -z "$YADM_REPO"    ]; then YADM_REPO="$YADM_DIR/repo.git"    ; fi
if [ -z "$YADM_CONFIG"  ]; then YADM_CONFIG="$YADM_DIR/config"    ; fi
if [ -z "$YADM_ENCRYPT" ]; then YADM_ENCRYPT="$YADM_DIR/encrypt"  ; fi
if [ -z "$YADM_ARCHIVE" ]; then YADM_ARCHIVE="$YADM_DIR/files.gpg"; fi
```

And created the following aliases for me (https://github.com/fdietze/dotfiles/blob/f7de4eba233bf303a76d0cf54d051826de3309ed/.sh_aliases#L15-L16):
```bash
alias  d='YADM_REPO=$HOME/projects/dotfiles         yadm -c core.excludesfile=~/.gitignore-dotfiles'
alias dp='YADM_REPO=$HOME/projects/dotfiles-private yadm -c core.excludesfile=~/.gitignore-dotfiles-private'
```

This works so far. Is there a better way?

**Comment by TheLocehiliosan** [comment]
I'm leery of changing *yadm*'s behavior so drastically based on environment variables. This is why I've implemented the `-Y`/`--yadm-dir` feature as a commandline argument.

Because of that change, I now have the scaffolding in place which would make it trivial to support `--yadm-repo`, `--yadm-config`, `--yadm-encrypt`, and `--yadm-archive`. I think I'd be more comfortable with that.

Would that work? Aliases would look like:

    alias  d='yadm --yadm-repo $HOME/projects/dotfiles         -c core.excludesfile=~/.gitignore-dotfiles'
    alias dp='yadm --yadm-repo $HOME/projects/dotfiles-private -c core.excludesfile=~/.gitignore-dotfiles-private'

In general, I think it is an edge-case for users to be modifying any of these values.

Unrelated... I am curious about your use of gitignore files. I've found that most need for those (when managing dotfiles) is mitigated by the configuration `status.showUntrackedFiles=no` _(this is yadm's default)_. I'm guessing you're using wildcards or `-A` when doing repo manipulations? Or is it for some other reason?

**Comment by fdietze** [comment]
Sure, the ```--yadm-repo``` option would also be perfect for me. Thanks for considering these fine-grained options!

No, I'm not using wildcards to manage my dotfiles. But when I want to see what I didn't track ```--untracked``` prints my whole home tree. This is just too much to work with. At that point I want to ignore most of the irrelevant files ([.gitignore-dotfiles](https://github.com/fdietze/dotfiles/blob/f7de4eba233bf303a76d0cf54d051826de3309ed/.gitignore-dotfiles)). This is a recent experiment, I don't know if this is a good idea. ```--untracked-files=normal``` also seems like a promising solution.

**Comment by TheLocehiliosan** [comment]
Yes, `yadm status -unormal` is the standard way I display the untracked files. (there's actually an item on this in the FAQ I have partially written).

I'll move ahead adding the options I mentioned above. I'm currently delayed because I'm writing a large number of unit tests—which should allow me to shove out future changes with a lot more confidence. Shouldn't be too long of a wait though.

I'll leave this issue open until I publish the change.

Cheers

**Comment by fdietze** [comment]
Thank you and take your time. My workaround is working, so I'm not waiting at all ;).

**Comment by TheLocehiliosan** [comment]
@fdietze I just pushed a new version to branch `dev`. This version should support the `--yadm-repo` option discussed above. Check it out and let me know if it works. I still need to write some more documentation before publishing a new version officially. It would also be good to know if you encounter any other issues, as I've done a good share of refactoring in this version.

Cheers

**Comment by fdietze** [comment]
@TheLocehiliosan Thank you, this is working! I will stay on the dev branch now and report any issues i encounter.
