### ISSUE TITLE
Asymmetric encryption

### ISSUE THREAD

**Issue by esphen** [TheLocehiliosan/yadm#7]
Hi,

I would very much like to use your program to organize my dotfiles; `yadm` seems like a really neat little utility! It seems to make it trivial to keep all my workstations in sync and also share my dotfiles with the world, which is a win-win.

There is a feature I cannot live without, however, and that is asymmetric encryption using public/private key pairs. Without asymmetric encryption I don't feel comfortable placing encrypted files alongside my dotfiles, and then I might as well just write bash scripts like I have done previously. I would love to see this in `yadm`, possibly as a configuration option like `yadm.gpg-encryption-key`, where if present uses a key pair instead of symmetric encryption.

Thanks a lot for the great program!

**Comment by TheLocehiliosan** [comment]
Thanks for the suggestion. I've contemplated asymmetric encryption before, but wasn't quite sure the best way to handle it. I mostly avoided it in the past, because I wanted users to have the convenience of bootstrapping "quickly", without a prerequisite of installing keys. However, I agree that asymmetric is more secure, and not subject to the same type of brute-force attacks without the private key.

Implementing as a configuration option seems like it would work OK. I think what you're suggesting is a configuration option to specify a "recipient" for the encrypted data. This would be easiest to implement if I only support a single recipient (at least for an initial version of the feature). I need to catch-up on documenting the recent development version, and then I'll put together support for asymmetric encryption. I'll update this issue again when I have something to test.

Cheers
