### ISSUE TITLE
Include DISTRO in alternate selection

### ISSUE THREAD

**Issue by sheychen290** [TheLocehiliosan/yadm#72]
With #68, alt files became even more complicated.
Exemple: ```myfile##%.%.Paul```

A simple solution should be "keys".

Value | Key
----- | ------
CLASS | ~
SYS | $
HOST | @
USER | ?
DISTRO | *

Exemple: ```myfile##?Paul

**Comment by TheLocehiliosan** [comment]
I think that you are suggesting an alternative format for alt files. So that if you only want to select based on OS, you would use `file##$Linux`. Is that correct? It is not clear how this relates to jinja template alternates (as all those files must end in `##yadm.j2`).

**Comment by sheychen290** [comment]
Yes, it's exactly that.
Post edited.

**Comment by TheLocehiliosan** [comment]
Again, it is unclear to me how this is related to Jinja templates. I think I'm missing something. Can you explain more completely?

**Comment by sheychen290** [comment]
There is no link with jinja.
#68 add YADM_DISTRO also in alt name, so we have to use ```file##%.%.%.Arch``` which is too much.

**Comment by TheLocehiliosan** [comment]
OK, the subject of this issue was "Rework alt-jinja" and #68 only exposed `YADM_DISTRO` to Jinja templates, so that led to my confusion. Currently (even in the dev branch which includes #68) the only supported alternate file patterns are `##CLASS.OS.HOSTNAME.USER` or `##OS.HOSTNAME.USER`. "Distro" is not supported in the alternate patterns. A pattern like `##file##%.%.%.Arch` merely matches a username of `Arch`.

I could see the possibility of supporting "Distro" as a more specific replacement for "OS". The current order of precedence for matching alternate files is:

    ##CLASS.OS.HOSTNAME.USER
    ##CLASS.OS.HOSTNAME
    ##CLASS.OS
    ##CLASS
    ##OS.HOSTNAME.USER
    ##OS.HOSTNAME
    ##OS
    ##

If "Distro" was added as a more specific substitute for "OS" the precedence of patterns would look more like this:

    ##CLASS.DISTRO.HOSTNAME.USER
    ##CLASS.OS.HOSTNAME.USER
    ##CLASS.DISTRO.HOSTNAME
    ##CLASS.OS.HOSTNAME
    ##CLASS.DISTRO
    ##CLASS.OS
    ##CLASS
    ##DISTRO.HOSTNAME.USER
    ##OS.HOSTNAME.USER
    ##DISTRO.HOSTNAME
    ##OS.HOSTNAME
    ##DISTRO
    ##OS
    ##

Such a change would make `file##Arch` linked in favor of `file##Linux`. Is this closer to what you're looking for?

**Comment by sheychen290** [comment]
It seems good.

But ##value should be CLASS, OS or DISTRO.

Exemple:
```file##Debian.%.Paul``` should be:
- CLASS=Debian and HOSTNAME=Paul
- DISTRO=Debian and USER=Paul
- OS=Debian and USER=Paul

It's work but not really strict.

So there is two way:
- Keep only ```##CLASS.OS.DISTRO.HOSTNAME.USER``` and wildcard but a simple USER=? became ```##%.%.%.%.Paul```.
- With key ```file##?Paul```

**Comment by TheLocehiliosan** [comment]
`##value` would resolve to CLASS, OS, or DISTRO (in that order). The intention behind the order of precedence for all matching patterns is to have the most specific definition win. DISTRO ("Arch") is more specific than OS ("Linux").

I realize there _could_ be a more explicit definition for files, but I'm not yet convinced that adding an additional form for alternate file classification is a good thing to do. The current implementation is geared toward the most common use-cases.

I'm curious about the use-case you have which is driving the desire for classification based on distro. Could you explain it a bit?

**Comment by TheLocehiliosan** [comment]
@sheychen290 - I'm not sure if you missed my last comment, but I would really like to understand your situation. What is the use-case which that needs to the classification based on distro?

**Comment by gfa** [comment]
Hello @TheLocehiliosan 

I want to, kindly, request the same feature, being able to match ##DISTRO. My use case for it is I have multiple debian machines and a single (soon to have 2) centos machines. 
So for some files now I have

```
file##Work (centos machine)
file##pi (a debian machine)
file##pinebook (another debian machine)
file##Linux.io (another debian machine running an older version of yadm without local classes support)
```

since `file` looks the same for all debian machines, i'd like to have

```
file##Centos
file##Debian
```

and be done with it

thanks!

PS: i know there are workarounds like defining the same local class for all debian machines, but that would force me to manage all of them the same way and I don't want that, I'm also aware of the jinja2 support and its something i'll look into soon.

**Comment by gfa** [comment]
The order of precedence you mention on https://github.com/TheLocehiliosan/yadm/issues/72#issuecomment-313679197 makes total sense to me

Bah, to my use-case (single user of yadm on a single user machine), for my other use-case (user in a  multiple users machine) my yadm usage is much more simple

**Comment by TheLocehiliosan** [comment]
@gfa I plan to add DISTRO to the alternate selection patterns (when `lsb_release` is present). The patterns will look like:

    ##CLASS.DISTRO.HOSTNAME.USER
    ##CLASS.OS.HOSTNAME.USER
    ##CLASS.DISTRO.HOSTNAME
    ##CLASS.OS.HOSTNAME
    ##CLASS.DISTRO
    ##CLASS.OS
    ##CLASS
    ##DISTRO.HOSTNAME.USER
    ##OS.HOSTNAME.USER
    ##DISTRO.HOSTNAME
    ##OS.HOSTNAME
    ##DISTRO
    ##OS
    ##

**Comment by malikoth** [comment]
I don't see anything recent from @sheychen290, so I'm going to provide my own take on this.  I believe this is actually what he is trying to describe, but I wouldn't presume to put words in his mouth.  At the very least, this is what I would love to see based on my recent adoption of yadm.

Rather than having a scheme with 14 matching patterns, which are not at all unique, I'd rather have a way to provide key-value pairs that explicitly identify the file with whatever pieces of information you want to provide.  This would not be unlike query-string parameters in a URL.  I believe sheychen is proposing to use the symbols at the top as the keys in this mapping.  I personally think those symbols would not be ideal, first because they convey no meaning, secondly because many of those characters mean things to the shell.  I'd rather use perhaps three-letter identifiers.

For example, instead of `myfile.txt##%.%.Paul` I could just put `myfile.txt##USR:Paul`.  You could use a single `#` as the delimiter between further k-v pairs, e.g., `myfile.txt##USR:Paul#DST:Ubuntu#CLS:Work`

Some pros:
* This would make the ordering irrelevant, and I could stop coming here to look up the patterns again.
* This would also make it trivial to add support for new identifying keywords like DISTRO, ID, ID_LIKE etc.

Some cons:
* Backwards incompatible.  Obviously.  I'm not sure how you would address this.  Simply maintain the patterns when one is matched, otherwise use the k-v system?  Make a 2.0 release that deprecates the patterns after some amount of time?  I don't know.
* Makes file names longer.  This personally wouldn't bother me much, but I don't know about other people.

**Comment by TheLocehiliosan** [comment]
Thanks for the feedback @malikoth.

I think when only discussing the user interface there wouldn't be much trouble supporting a key/value scheme for alternate files. I don't even think it would too much trouble with backwards compatibility, as the format could be created such that the processing falls back to the original scheme if the supported "keys" are not part of the filename.

However, regardless of the notation, an order of precedence would still be required (which would continue to drive you to the documentation). Even with flexible key/value pairs, you can still create filenames such that multiple files are "valid", and it has to be worked out which is the "most appropriate".

More difficult is the complexity required to parse/process the alternates. Today the alternates processing takes advantage of Bash's ability to order the files easily. Supporting key/value notation would require more complicated parsing of the filenames. While I'm sure it is something that _could_ be accomplished, it could be difficult to code/maintain (especially with the limited requirements I've imposed for portability reasons). For example, associative arrays are available in Bash 4, but not in Bash 3. This complexity has to be weighed against the value gained.

Again, I'm not against the idea as a whole. But I can say I don't have a solid approach to handling the parsing in pure Bash 3. I will continue to think about how it could be supported though.

Since there is some apparent desire to support DISTRO, I will be adding it in `1.13.0`.

**Comment by TheLocehiliosan** [comment]
This feature is in the "develop" branch now. Some of the key/value concepts in the issue have shaped the new 2.0.0 al system.
