### ISSUE TITLE
Feature: Allow storing alternates elsewhere

### ISSUE THREAD

**Issue by luzat** [TheLocehiliosan/yadm#90]
It would be nice if alternates could additionally be stored in `$YADM_ALT_PATH/$alt_path` instead of just `$YADM_WORK/$alt_path`. This would mainly allow for somewhat cleaner directories, because I for example might not want to have all the macOS files generally appear in my Linux `~` or in my `~/bin`, where the `##` files will appear in tab completion without additional work on that.

A configuration option such as yadm.alt_path (possibly with a default of `~/.yadm/alt`) could be considered with the result of checking both paths if set.

A basic implementation in `alt()` does not look too hard, but there are probably some caveats. One is that the `~/parent` might not yet exist if `~/.yadm/alt/parent` does; would a simple `mkdir -p` already cover that case?

Is there any interest in this feature? If there is I may prepare a pull request, otherwise just a fork if this would otherwise not happen soon anyway.

**Comment by TheLocehiliosan** [comment]
I could see the appeal to storing alternate files outside of the work-tree. Here's a few thoughts I have on the idea.

1. There are some types of files which need to be secured and the entire path leading up to the file need to be secured, like ssh and gpg related files. It is probably necessary to treat the same paths in an alternate storage directory the same way.
2. I want to maintain compatibility with the current tool so continuing to support the work-tree will certainly be necessary.
3. If the alternate storage directory is also under the work-tree, the "standard" alternate processing would need to ignore the files under the alternate storage directory. For example, if your suggested path was used, a file called `.yadm/alt/path/file##` _should not_ result in the link `.yadm/alt/path/file` while a file called `.yadm/encrypt##` _should_ result in the link `.yadm/encrypt`.
4. There may be some impact on how [issue 65](https://github.com/TheLocehiliosan/yadm/issues/65) gets implemented. That feature is essentially removing alt-linked files, if the alternate file is no longer valid or exists.
5. I agree that a basic implementation wouldn't be too bad. As is usually the case, making tests for the new feature is much more complicated. 🙂 I do have some ideas on how the current tests could be leveraged to work on both paths.

**Comment by mclang** [comment]
This would be good feature to have!

Currently I solved this issue by creating `.yadm/alt-files` directory and putting my alternate files like gitconfig inside it. Then I created yadm bootstrap that when run makes the necessary linking. This works currently pretty well with only couple of files but will become cumbersome I think when I add more files.

So I will follow this feature closely.

**Comment by luzat** [comment]
I have created a basic implementation in luzat/yadm@727e656ceba0a063f8f355867a965380d1b49904 (https://github.com/luzat/yadm/tree/dev). It does not come with tests or documentation, but passes all existing tests (after adjusting for the additional option/argument). For caveats, read the commit message. If you are interested in trying it out you can check out or download yadm from my dev branch.

It is using `~/.yadm/alt` by default, but this can be overriden by e.g. `yadm config yadm.alt .yadm/alt-files` or `yadm --yadm-alt ~/.yadm/.alt-files`. Only alternate files will be considered, so `~/.yadm/alt/foo##` will result in a link at `~/foo`, but `~/.yadm/alt/foo` will not.

I am not sure when I will find time to improve upon that, but I will try to reasonably fix issues as encountered and follow. In the long run a PR would of course be nice.

**Comment by TheLocehiliosan** [comment]
@luzat Can you create a PR based off the `dev` branch? I don't mind completing the tests and documentation. I think this is a feature that could be worked into the `1.13.0` release. I am planning to release `1.12.0` before adding anything more. (I might ask you to rebase after the `1.12.0` release, but it sounds like you're already committed to keeping this change up-to-date).

**Comment by malikoth** [comment]
Thank you for working on this.  This is my biggest disappointment with yadm, because I have several OSX specific files that I'd love to have disappear when I `yadm clone` on Debian.

**Comment by Meizikyn** [comment]
This shouldn't be difficult to implement I think, maybe a check for files under $YADM_DIR, or a check against any yadm-specific config files otherwise specified outside of $YADM_DIR.

I have this sort-of working on my setup by adding a bash_rematch section to the regexp with an $alt_prefix and changing the new_link to bash_rematch[2].

When I have time I'll try to add directory creation, symlink removal in issue #65 , and possibly safe removal of directories created by yadm if they are otherwise empty.

**Comment by futile** [comment]
Hi, just wanted to ask what the status on this is? Thanks!

**Comment by TheLocehiliosan** [comment]
@futile This is something I am for sure going to get into **yadm**. However, I'm actually cooking up some major changes which have an impact on it.

First, **yadm** is going to begin using the XDG_CONFIG_HOME scheme to identify its configuration directory. Since this is a major compatibility change, I'm going to push the version to 2.0.0 with this release. Since I'm already going to implement compatibly changes, at the same time I plan to change the syntax used to specify alternates. Instead of positional arguments, they will be labels on the end of files. (something like this: `filename##o.Darwin,u.tbyrne` where the order doesn't matter.

This change will remove the need for wildcards, allow for more succinctly defined alternates, solve some of the existing bugs, and allow for extending the dictionary of supported alternate "fields" without breaking existing alternates.

I did take a stab at writing the tests for the PR referenced in this issue, but it quickly because very difficult. The new system of alternates will be far easier to design tests for (including the special directory for alternate files).

**Comment by TheLocehiliosan** [comment]
This feature is now complete, and part of the `develop` branch.
