### ISSUE TITLE
Passing arguments to bootstrap program?

### ISSUE THREAD

**Issue by anowlcalledjosh** [TheLocehiliosan/yadm#95]
It would be awesome if stuff like `yadm bootstrap --minimal` was possible, but currently any arguments to `yadm bootstrap` are just discarded.

From a very quick look, it seems like all it would need is changing [line 245](https://github.com/TheLocehiliosan/yadm/blob/09a018ea5a081923a8d39f5f0bb02b138284230a/yadm#L245) from

```sh
  exec "$YADM_BOOTSTRAP"
```

to

```sh
  exec "$YADM_BOOTSTRAP" "$@"
```

(but there may well be things I haven't noticed that will make that not work properly).

**Comment by TheLocehiliosan** [comment]
I was just looking to add this to yadm. However, it feels inconsistent to allow the `yadm bootstrap` command to provide parameters, because the bootstrap can also be invoked automatically during a `yadm clone`. There doesn't seem to be an elegant way to add the parameters to the clone command as well.

@anowlcalledjosh - I think the best way to handle this at the moment is to pass an environment variable before the bootstrap or clone command.

Like this:

```
minimal=true yadm bootstrap
```
